#include "graphics/projections/axonometricprojection.h"
#include "graphics/projections/obliqueprojection.h"
#include "graphics/projections/perspectiveprojection.h"
#include "graphics/projections/frontalprojection.h"
#include "graphics/projections/profileprojection.h"
#include "graphics/projections/horizontalprojection.h"
